---
# Run the setup tasks for the selinux workshop
#

- name: "SELinux workshop setup"
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  tasks:

  - name: "Copy the testaudit file"
    copy:
      src: files/testaudit
      dest: /root/testaudit



