---
# Run the setup tasks for the selinux workshop
#

- name: "SELinux workshop setup"
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  tasks:

  - name: "Copy the testaudit file"
    ansible.builtin.copy:
      src: files/testaudit
      dest: /root/testaudit

  - name: "Copy the vimrc file"
    ansible.builtin.copy:
      src: files/vimrc
      dest: /home/ec2-user/.vimrc


  - name: "Install required utilities"
    ansible.builtin.yum:
      name: 
        - "policycoreutils-devel"
        - "policycoreutils-python-utils"
        - "setools-console"
        - "vim"
      state: present

